/**
 * Interactive first-time setup for audio/video calls: generates a TURN
 * shared secret, detects the server's public IP, writes the TURN_* vars
 * into `.env` itself, installs and configures coturn natively via
 * apt/systemd (the production deploy target is bare-metal/systemd, not
 * docker-compose - see scripts/update.sh), prints the router
 * port-forwarding instructions (which it cannot do itself), and finally
 * enables the `calls_enabled` instance setting. Requires root (apt install,
 * writing /etc/turnserver.conf, systemctl) and a real Linux host - not
 * something that can be dry-run in a dev/sandbox environment.
 *
 * Usage:
 *   sudo npm run setup-calls --workspace=packages/server
 *
 * Re-running this script is safe but not incremental: it overwrites
 * /etc/turnserver.conf and restarts coturn every time rather than diffing
 * against a previous run (see the plan's "open risks" section).
 */
import crypto from "node:crypto";
import fs from "node:fs";
import readline from "node:readline/promises";
import { execFileSync } from "node:child_process";
import { setCallsEnabled } from "../modules/instanceSettings/service.js";
import { sqlite } from "../db/client.js";
import { envFilePath } from "../env.js";

const TURN_LISTEN_PORT = 3478;
const DEFAULT_MIN_PORT = 49160;
const DEFAULT_MAX_PORT = 49200;
const IP_LOOKUP_TIMEOUT_MS = 5000;

function run(command: string, args: string[]): void {
  execFileSync(command, args, { stdio: "inherit" });
}

function tryRun(command: string, args: string[]): boolean {
  try {
    run(command, args);
    return true;
  } catch {
    return false;
  }
}

async function detectPublicIp(): Promise<string | null> {
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), IP_LOOKUP_TIMEOUT_MS);
    const response = await fetch("https://api.ipify.org", { signal: controller.signal });
    clearTimeout(timeout);
    if (!response.ok) return null;
    return (await response.text()).trim();
  } catch {
    return null;
  }
}

/** Read-modify-write `.env`, preserving every existing line/comment/ordering - only touches the keys we're upserting. */
function upsertEnvVars(values: Record<string, string>): void {
  const existing = fs.existsSync(envFilePath) ? fs.readFileSync(envFilePath, "utf8") : "";
  const lines = existing.length > 0 ? existing.split("\n") : [];
  const remainingKeys = new Set(Object.keys(values));

  const updatedLines = lines.map((line) => {
    const match = /^([A-Z0-9_]+)=/.exec(line);
    if (!match) return line;
    const key = match[1]!;
    if (!remainingKeys.has(key)) return line;
    remainingKeys.delete(key);
    return `${key}=${values[key]}`;
  });

  if (remainingKeys.size > 0) {
    if (updatedLines.length > 0 && updatedLines[updatedLines.length - 1] !== "") updatedLines.push("");
    updatedLines.push("# Added by `npm run setup-calls` - see docs/DEPLOYMENT.md");
    for (const key of remainingKeys) updatedLines.push(`${key}=${values[key]}`);
  }

  fs.writeFileSync(envFilePath, updatedLines.join("\n"));
}

function turnServerConf(secret: string, realm: string, minPort: number, maxPort: number): string {
  return `# Generated by \`npm run setup-calls\` (Notorious) - safe to re-run the
# wizard to regenerate this file, but hand edits will be overwritten.
listening-port=${TURN_LISTEN_PORT}
fingerprint
use-auth-secret
static-auth-secret=${secret}
realm=${realm}
total-quota=100
stale-nonce=600
min-port=${minPort}
max-port=${maxPort}
no-multicast-peers
no-cli
`;
}

async function main(): Promise<void> {
  console.warn("=== Notorious calls setup ===\n");
  console.warn("This will: modify .env, install the `coturn` package via apt, write /etc/turnserver.conf, and enable a systemd service.\n");

  if (process.platform !== "linux") {
    console.error("This wizard only supports Linux (apt + systemd). Set TURN up manually and use `npm run enable-calls` once it's running.");
    process.exitCode = 1;
    return;
  }
  if (typeof process.getuid === "function" && process.getuid() !== 0) {
    console.error("Run this as root (sudo npm run setup-calls --workspace=packages/server) - it needs to install packages and write /etc/turnserver.conf.");
    process.exitCode = 1;
    return;
  }

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  try {
    const proceed = await rl.question("Continue? [y/N] ");
    if (proceed.trim().toLowerCase() !== "y") {
      console.warn("Aborted.");
      return;
    }

    const turnSecret = crypto.randomBytes(32).toString("hex");
    console.warn("\nGenerated a new TURN shared secret.");

    console.warn("Detecting public IP…");
    const detectedIp = await detectPublicIp();
    if (detectedIp) console.warn(`Detected public IP: ${detectedIp}`);
    else console.warn("Could not auto-detect a public IP (offline, or the lookup service is unreachable).");

    const domainAnswer = await rl.question(`Domain or public IP this server is reachable at${detectedIp ? ` [${detectedIp}]` : ""}: `);
    const turnDomain = domainAnswer.trim() || detectedIp;
    if (!turnDomain) {
      console.error("A domain or public IP is required - re-run once you know it.");
      process.exitCode = 1;
      return;
    }

    const portRangeAnswer = await rl.question(`Relay port range (UDP) [${DEFAULT_MIN_PORT}-${DEFAULT_MAX_PORT}]: `);
    const [minPortStr, maxPortStr] = portRangeAnswer.trim() ? portRangeAnswer.trim().split("-") : [String(DEFAULT_MIN_PORT), String(DEFAULT_MAX_PORT)];
    const minPort = Number(minPortStr) || DEFAULT_MIN_PORT;
    const maxPort = Number(maxPortStr) || DEFAULT_MAX_PORT;

    console.warn("\nWriting .env…");
    upsertEnvVars({
      TURN_SECRET: turnSecret,
      TURN_DOMAIN: turnDomain,
      TURN_REALM: turnDomain,
      TURN_MIN_PORT: String(minPort),
      TURN_MAX_PORT: String(maxPort),
    });

    console.warn("Installing coturn (apt-get install -y coturn)…");
    run("apt-get", ["update"]);
    run("apt-get", ["install", "-y", "coturn"]);

    console.warn("Writing /etc/turnserver.conf…");
    fs.writeFileSync("/etc/turnserver.conf", turnServerConf(turnSecret, turnDomain, minPort, maxPort));

    // Debian/Ubuntu's coturn package ships disabled by default until this flag is flipped.
    const defaultsPath = "/etc/default/coturn";
    if (fs.existsSync(defaultsPath)) {
      const defaults = fs.readFileSync(defaultsPath, "utf8");
      const updated = /^TURNSERVER_ENABLED=/m.test(defaults)
        ? defaults.replace(/^#?\s*TURNSERVER_ENABLED=.*/m, "TURNSERVER_ENABLED=1")
        : `${defaults}\nTURNSERVER_ENABLED=1\n`;
      fs.writeFileSync(defaultsPath, updated);
    }

    console.warn("Enabling and starting coturn…");
    run("systemctl", ["enable", "--now", "coturn"]);

    const isActive = tryRun("systemctl", ["is-active", "--quiet", "coturn"]);
    if (!isActive) {
      console.error("\ncoturn did not come up healthy. Check the logs before continuing:");
      console.error("  journalctl -u coturn -n 50 --no-pager\n");
      console.error("Not enabling calls - fix coturn and re-run this wizard.");
      process.exitCode = 1;
      return;
    }
    console.warn("coturn is running.");

    console.warn(`
=== Router port forwarding required ===
Forward these to this machine's LAN IP - this cannot be automated:
  UDP ${TURN_LISTEN_PORT}
  UDP ${minPort}-${maxPort}
`);
    const portsForwarded = await rl.question("Have you completed port forwarding on your router? [y/N] ");
    if (portsForwarded.trim().toLowerCase() !== "y") {
      console.warn("\nNot enabling calls yet. Once you've forwarded the ports, run: npm run enable-calls --workspace=packages/server");
      return;
    }

    await setCallsEnabled(true);
    console.warn("\nCalls are now ENABLED.");
    console.warn("Restart the app server so it picks up the new .env values: systemctl restart notorious");
  } finally {
    rl.close();
  }
}

void main()
  .catch((error) => {
    console.error("Calls setup failed:", error instanceof Error ? error.message : error);
    process.exitCode = 1;
  })
  .finally(() => sqlite.close());
