import {
  FileText,
  FolderKanban,
  CheckSquare,
  User,
  Book,
  Calendar,
  Building2,
  Paperclip,
  Table2,
  Layers,
  Sparkles,
  Search,
  Settings,
  Plus,
  ChevronDown,
  ChevronRight,
  GripVertical,
  Trash2,
  MoreHorizontal,
  X,
  Sun,
  Moon,
  Download,
  Upload,
  LayoutGrid,
  List as ListIcon,
  Rows3,
  GanttChartSquare,
  Image as ImageIcon,
  Pin,
  PinOff,
  Menu,
  Clock,
  LayoutDashboard,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  "file-text": FileText,
  "folder-kanban": FolderKanban,
  "check-square": CheckSquare,
  user: User,
  book: Book,
  calendar: Calendar,
  building: Building2,
  paperclip: Paperclip,
  table: Table2,
  layers: Layers,
  sparkles: Sparkles,
  search: Search,
  settings: Settings,
  plus: Plus,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "grip-vertical": GripVertical,
  trash: Trash2,
  more: MoreHorizontal,
  close: X,
  sun: Sun,
  moon: Moon,
  download: Download,
  upload: Upload,
  board: LayoutGrid,
  list: ListIcon,
  rows: Rows3,
  timeline: GanttChartSquare,
  image: ImageIcon,
  pin: Pin,
  "pin-off": PinOff,
  menu: Menu,
  clock: Clock,
  "layout-dashboard": LayoutDashboard,
};

export function Icon({ name, className }: { name: string; className?: string }) {
  const Component = ICONS[name] ?? FileText;
  return <Component className={className ?? "h-4 w-4"} />;
}
