import type { VermieterAllocationKey, VermieterBillingMode, VermieterEstimationMethod } from "../db/types.js";
import { getCostCategory } from "../db/costCategories.js";
import { resolveCircuitConsumption, type UnitConsumptionInput } from "./meterSubstitute.js";

/**
 * Pure calculation engine for a Nebenkostenabrechnung (§556 BGB operating-
 * cost statement). Everything here is deliberately side-effect-free and
 * takes plain in-memory data - `services/statements.ts` is the only caller,
 * and does all the SQLite reads/writes around it. Kept pure so the
 * allocation math (which ends up on a document a tenant can legally
 * dispute) can be reasoned about/tested in isolation from storage.
 *
 * A statement is a point-in-time legal snapshot - once generated its
 * `vermieter_statement_lines`/`vermieter_statement_tenant_summaries` rows
 * are never recomputed live, only re-generated by running this engine again
 * (see statements.ts).
 *
 * Cost circuits (Abrechnungskreise): every receipt belongs to a circuit
 * (`CalcReceipt.costCircuitId`), and a circuit only spans a subset of a
 * property's units (`CalcCostCircuit.unitIds`) - e.g. units with their own
 * electric Durchlauferhitzer simply aren't members of the
 * Zentralheizung/Warmwasser circuit, so they're excluded from both the cost
 * pool and its participant/denominator set entirely. Grouping is now
 * per-(circuit, category) rather than per-(property, category); everything
 * else (day-proration, vacancy-to-landlord bucket, the HeizkostenV 70/30
 * split) is unchanged in spirit, just re-scoped to a circuit's unit list
 * instead of the whole property's.
 */

export interface CalcUnit {
  id: string;
  sizeSqm: number;
}

/** A property's Abrechnungskreis (cost circuit) - see the module-level doc comment above. */
export interface CalcCostCircuit {
  id: string;
  unitIds: string[];
}

/** One lease's coverage of a unit, clipped to the statement period. `personCount` is the lease's explicit `person_count` field (falls back to linked-tenant count only if that's somehow null - see services/leases.ts and db/types.ts::VermieterLeaseRow). */
export interface CalcLeaseSegment {
  leaseId: string;
  unitId: string;
  /** Clipped to the statement period - always >= periodStart and <= periodEnd. */
  segmentStart: string;
  segmentEnd: string;
  personCount: number;
}

export interface CalcReceipt {
  id: string;
  costCategoryKey: string;
  amountCents: number;
  allocationKeyOverride: VermieterAllocationKey | null;
  targetUnitId: string | null;
  /** Which Abrechnungskreis this receipt's cost pool belongs to - always a concrete circuit id (services/receipts.ts resolves the property's default circuit when none was given). */
  costCircuitId: string;
}

/** Per (cost circuit, cost category) external-billing opt-in - see migrations/0012 and services/externalBilling.ts. Only pairs with `billingMode === 'external_provider'` change engine behavior; everything else stays in 'calculated' mode by omission. */
export interface CalcCircuitCategorySetting {
  costCircuitId: string;
  costCategoryKey: string;
  billingMode: VermieterBillingMode;
  providerName: string | null;
}

/**
 * One landlord-transcribed per-unit amount from an external provider's own
 * finished statement (see migrations/0012). `periodStart`/`periodEnd` are
 * the PROVIDER's own period, which need not exactly match the statement's -
 * see computeExternalProviderLines's day-overlap proration.
 */
export interface CalcExternalAllocation {
  unitId: string;
  costCircuitId: string;
  costCategoryKey: string;
  periodStart: string;
  periodEnd: string;
  amountCents: number;
}

/**
 * Per-unit metered consumption within the period, keyed by the meter's
 * `type` (see services/meters.ts::consumptionInPeriod, summed across all
 * meters of that type in the unit). `null` means "no meter, or no reading
 * pair bracketing the period" - distinct from a real `0`, since it drives
 * the §9a HeizkostenV substitute-value resolution (services/
 * meterSubstitute.ts) rather than being silently treated as zero
 * consumption. `prior*` fields are the same unit's own metered consumption
 * in the prior comparable period (see services/meters.ts::
 * priorComparablePeriod), used for the "own history" substitute branch.
 */
export interface CalcConsumptionByUnit {
  unitId: string;
  heating: number | null;
  coldWater: number | null;
  hotWater: number | null;
  priorHeating: number | null;
  priorColdWater: number | null;
  priorHotWater: number | null;
}

export interface StatementLineResult {
  unitId: string;
  costCategoryKey: string;
  allocationKeyUsed: VermieterAllocationKey;
  totalPropertyCostCents: number;
  unitShareCents: number;
  vacancyShareCents: number;
  daysOccupied: number;
  daysTotal: number;
  /** True when unitShareCents was derived from a §9a HeizkostenV substitute value rather than a real meter reading. Always false for non-consumption allocation keys. */
  isEstimated: boolean;
  /** 'metered' | one of the substitute methods for consumption-based lines; null for every other allocation key. */
  estimationMethod: VermieterEstimationMethod | null;
  /** The unit's own raw allocation-basis value (sqm/persons/1/resolved consumption) that produces this line's percentage - see pdf/explanationText.ts. Null for fixed_manual/external_provider lines, which have no allocation-key fraction to explain. */
  basisNumerator: number | null;
  /** The circuit-wide total of that same basis - the denominator paired with basisNumerator. */
  basisDenominator: number | null;
  /** The metering-service name this line's cost was transcribed from - only set when allocationKeyUsed === 'external_provider'. */
  externalProviderName: string | null;
}

export interface TenantSummaryResult {
  unitId: string;
  leaseId: string;
  segmentStart: string;
  segmentEnd: string;
  totalAllocatedCostCents: number;
}

export interface StatementCalculationInput {
  periodStart: string; // YYYY-MM-DD
  periodEnd: string; // YYYY-MM-DD
  units: CalcUnit[];
  costCircuits: CalcCostCircuit[];
  leaseSegments: CalcLeaseSegment[];
  receipts: CalcReceipt[];
  consumption: CalcConsumptionByUnit[];
  /** Verbrauchskosten share of Heizung costs, 0-100. HeizkostenV §7 mandates at least 50%, standard/default 70. The remaining share is Grundkosten, allocated by qm. */
  heatingConsumptionSharePercent: number;
  /** Per (circuit, category) external-billing opt-ins - see CalcCircuitCategorySetting's doc comment. Only entries with billingMode === 'external_provider' change anything; everything else is 'calculated' by omission. */
  circuitCategorySettings: CalcCircuitCategorySetting[];
  /** Landlord-transcribed external per-unit amounts - see CalcExternalAllocation's doc comment. Only consulted for (circuit, category) pairs actually in 'external_provider' mode. */
  externalAllocations: CalcExternalAllocation[];
}

export interface StatementCalculationResult {
  lines: StatementLineResult[];
  tenantSummaries: TenantSummaryResult[];
}

function daysBetweenInclusive(startIso: string, endIso: string): number {
  const start = new Date(`${startIso}T00:00:00Z`).getTime();
  const end = new Date(`${endIso}T00:00:00Z`).getTime();
  return Math.max(0, Math.round((end - start) / 86_400_000) + 1);
}

function clampDateRange(aStart: string, aEnd: string, bStart: string, bEnd: string): { start: string; end: string } | null {
  const start = aStart > bStart ? aStart : bStart;
  const end = aEnd < bEnd ? aEnd : bEnd;
  if (start > end) return null;
  return { start, end };
}

function roundCents(value: number): number {
  return Math.round(value);
}

interface CategoryBucket {
  costCircuitId: string;
  costCategoryKey: string;
  allocationKey: VermieterAllocationKey;
  totalCents: number;
}

/** Builds the `${circuitId}::${categoryKey}` lookup key shared by the external-billing exclusion set and computeExternalProviderLines. */
function circuitCategoryKey(costCircuitId: string, costCategoryKey: string): string {
  return `${costCircuitId}::${costCategoryKey}`;
}

/**
 * Groups receipts (excluding `fixed_manual`-overridden ones, which bypass
 * this entirely - see computeFixedManualLines - and excluding any
 * (circuit, category) pair opted into `external_provider` billing, which
 * bypasses the whole allocation-key pipeline in favor of transcribed
 * external amounts - see computeExternalProviderLines) into per-(circuit,
 * category, effective allocation key) cost buckets. A category can appear in
 * more than one bucket for the same circuit if some of its receipts were
 * individually overridden to a different allocation key, or if it has
 * receipts in more than one circuit.
 */
export function computeCategoryTotals(receipts: CalcReceipt[], externalModePairs: Set<string> = new Set()): Map<string, CategoryBucket> {
  const buckets = new Map<string, CategoryBucket>();
  for (const receipt of receipts) {
    if (receipt.allocationKeyOverride === "fixed_manual") continue; // handled separately, per-receipt
    if (externalModePairs.has(circuitCategoryKey(receipt.costCircuitId, receipt.costCategoryKey))) continue; // handled separately, see computeExternalProviderLines
    const category = getCostCategory(receipt.costCategoryKey);
    const allocationKey = receipt.allocationKeyOverride ?? category?.defaultAllocationKey ?? "sqm";
    const bucketKey = `${receipt.costCircuitId}::${receipt.costCategoryKey}::${allocationKey}`;
    const bucket = buckets.get(bucketKey);
    if (bucket) bucket.totalCents += receipt.amountCents;
    else buckets.set(bucketKey, { costCircuitId: receipt.costCircuitId, costCategoryKey: receipt.costCategoryKey, allocationKey, totalCents: receipt.amountCents });
  }
  return buckets;
}

interface UnitDayWeights {
  unitId: string;
  /** Sum over this unit's lease segments of (segment weight * segment days). */
  occupiedWeightDays: number;
  /** (daysTotal - daysOccupied) * referenceWeight - the weight-days attributable to no tenant at all. */
  vacancyWeightDays: number;
  daysOccupied: number;
  /** The single occupying lease's segment, when there's exactly one covering the whole occupied span - used to attribute a statement_line's `lease_id`. Mid-period tenant changes (>1 segment) leave this null; the per-tenant breakdown for those still comes from tenantSummaries. */
  soleLeaseId: string | null;
  /** The unit's own steady-state basis value (sqm / 1 / last-known headcount) - independent of days, this is the "your unit has X of the basis" numerator pdf/explanationText.ts shows alongside the day-occupied fraction. */
  referenceWeight: number;
}

/**
 * Computes, for each unit, how many "weight-days" it contributed within the
 * period under a day-proration model shared by the sqm/persons/units
 * allocation bases: each day of the period a unit is under lease
 * contributes `segmentWeight(basis, segment)`; each day it's vacant
 * contributes `referenceWeight(basis, unit)` to a *landlord-borne* vacancy
 * bucket instead of being redistributed to other units (see the module's
 * top-level spec: vacancy is never picked up by other tenants). For the
 * `sqm`/`units` bases the reference weight always equals the occupied
 * weight (a unit's size or "1" doesn't change with occupancy), so this
 * reduces exactly to "cost per weight-day, split into occupied/vacant by
 * day count" as specified. For `persons` there's no natural capacity for a
 * vacant unit, so the reference weight falls back to the unit's own last
 * known headcount within the period (or 1 if it was never occupied during
 * the period) - a documented simplification. `units` here is always the
 * circuit's member units, not necessarily the whole property.
 */
function computeUnitDayWeights(
  basis: "sqm" | "persons" | "units",
  units: CalcUnit[],
  leaseSegments: CalcLeaseSegment[],
  periodStart: string,
  periodEnd: string,
): UnitDayWeights[] {
  const daysTotal = daysBetweenInclusive(periodStart, periodEnd);

  return units.map((unit) => {
    const segments = leaseSegments.filter((s) => s.unitId === unit.id);
    let occupiedWeightDays = 0;
    let daysOccupied = 0;
    let lastPersonCount = 1;
    for (const segment of segments) {
      const clipped = clampDateRange(segment.segmentStart, segment.segmentEnd, periodStart, periodEnd);
      if (!clipped) continue;
      const segmentDays = daysBetweenInclusive(clipped.start, clipped.end);
      const weight = basis === "sqm" ? unit.sizeSqm : basis === "units" ? 1 : Math.max(1, segment.personCount);
      occupiedWeightDays += weight * segmentDays;
      daysOccupied += segmentDays;
      lastPersonCount = Math.max(1, segment.personCount);
    }
    const vacancyDays = Math.max(0, daysTotal - daysOccupied);
    const referenceWeight = basis === "sqm" ? unit.sizeSqm : basis === "units" ? 1 : lastPersonCount;
    const vacancyWeightDays = referenceWeight * vacancyDays;
    const soleLeaseId = segments.length === 1 ? (segments[0]?.leaseId ?? null) : null;

    return { unitId: unit.id, occupiedWeightDays, vacancyWeightDays, daysOccupied, soleLeaseId, referenceWeight };
  });
}

/** Allocates `totalCents` across `units` (a circuit's member units) for one of the day-prorated bases (sqm/persons/units). Also returns each unit's raw basis numerator/denominator (see UnitDayWeights.referenceWeight) for the PDF explanation's fraction display - independent of the cost split itself. */
function allocateByDayWeights(
  basis: "sqm" | "persons" | "units",
  totalCents: number,
  units: CalcUnit[],
  leaseSegments: CalcLeaseSegment[],
  periodStart: string,
  periodEnd: string,
): { unitId: string; unitShareCents: number; vacancyShareCents: number; daysOccupied: number; basisNumerator: number; basisDenominator: number }[] {
  const weights = computeUnitDayWeights(basis, units, leaseSegments, periodStart, periodEnd);
  const totalWeightDays = weights.reduce((sum, w) => sum + w.occupiedWeightDays + w.vacancyWeightDays, 0);
  const basisDenominator = weights.reduce((sum, w) => sum + w.referenceWeight, 0);
  if (totalWeightDays <= 0) {
    return weights.map((w) => ({ unitId: w.unitId, unitShareCents: 0, vacancyShareCents: 0, daysOccupied: w.daysOccupied, basisNumerator: w.referenceWeight, basisDenominator }));
  }
  return weights.map((w) => ({
    unitId: w.unitId,
    unitShareCents: roundCents((totalCents * w.occupiedWeightDays) / totalWeightDays),
    vacancyShareCents: roundCents((totalCents * w.vacancyWeightDays) / totalWeightDays),
    daysOccupied: w.daysOccupied,
    basisNumerator: w.referenceWeight,
    basisDenominator,
  }));
}

function unitsById(units: CalcUnit[]): Map<string, CalcUnit> {
  return new Map(units.map((u) => [u.id, u]));
}

/** Builds the §9a HeizkostenV resolver input for one meter kind, scoped to a circuit's member units. */
function buildConsumptionInputs(
  circuitUnits: CalcUnit[],
  consumption: CalcConsumptionByUnit[],
  pick: (c: CalcConsumptionByUnit) => number | null,
  pickPrior: (c: CalcConsumptionByUnit) => number | null,
): UnitConsumptionInput[] {
  const byUnit = new Map(consumption.map((c) => [c.unitId, c]));
  return circuitUnits.map((unit) => {
    const entry = byUnit.get(unit.id);
    return {
      unitId: unit.id,
      sizeSqm: unit.sizeSqm,
      currentPeriodValue: entry ? pick(entry) : null,
      priorPeriodValue: entry ? pickPrior(entry) : null,
    };
  });
}

/**
 * Heizkostenverordnung §7: heating costs must be split into a
 * consumption-independent "Grundkosten" portion (allocated like a normal
 * qm-based cost) and a consumption-dependent "Verbrauchskosten" portion
 * (allocated by each unit's resolved heat consumption - real metered value
 * or, per §9a, a substitute - see services/meterSubstitute.ts), with the
 * consumption portion required to be 50-70% - 70/30 is the statutory
 * standard split absent a differing agreement, hence the default here.
 * Both portions are scoped to `circuitUnits` (the circuit's member units),
 * not necessarily the whole property. Water/electricity `consumption`-key
 * categories skip this split entirely and allocate 100% by resolved
 * consumption (see computeConsumptionLines).
 */
function computeHeatingLines(
  totalCents: number,
  circuitUnits: CalcUnit[],
  leaseSegments: CalcLeaseSegment[],
  consumption: CalcConsumptionByUnit[],
  periodStart: string,
  periodEnd: string,
  consumptionSharePercent: number,
): StatementLineResult[] {
  const daysTotal = daysBetweenInclusive(periodStart, periodEnd);
  const verbrauchCents = roundCents((totalCents * consumptionSharePercent) / 100);
  const grundCents = totalCents - verbrauchCents;

  const grundShares = allocateByDayWeights("sqm", grundCents, circuitUnits, leaseSegments, periodStart, periodEnd);

  const consumptionInputs = buildConsumptionInputs(
    circuitUnits,
    consumption,
    (c) => c.heating,
    (c) => c.priorHeating,
  );
  const resolved = resolveCircuitConsumption(consumptionInputs);
  const resolvedByUnit = new Map(resolved.map((r) => [r.unitId, r]));
  const totalConsumption = resolved.reduce((sum, r) => sum + r.value, 0);

  const lines: StatementLineResult[] = [];
  for (const unit of circuitUnits) {
    const grund = grundShares.find((g) => g.unitId === unit.id)!;
    lines.push({
      unitId: unit.id,
      costCategoryKey: "heizung",
      allocationKeyUsed: "sqm",
      totalPropertyCostCents: grundCents,
      unitShareCents: grund.unitShareCents,
      vacancyShareCents: grund.vacancyShareCents,
      daysOccupied: grund.daysOccupied,
      daysTotal,
      isEstimated: false,
      estimationMethod: null,
      basisNumerator: grund.basisNumerator,
      basisDenominator: grund.basisDenominator,
      externalProviderName: null,
    });

    // Verbrauchskosten: proportional to each unit's resolved consumption
    // (real metered value or §9a substitute). If nobody in the circuit has
    // any consumption data at all (totalConsumption <= 0 even after
    // substitution - shouldn't normally happen once the sqm-fallback branch
    // kicks in, but guards an empty-circuit edge case), the cost is simply
    // left unallocated/0 rather than guessed.
    const resolvedUnit = resolvedByUnit.get(unit.id);
    const unitShare = totalConsumption > 0 && resolvedUnit ? roundCents((verbrauchCents * resolvedUnit.value) / totalConsumption) : 0;
    lines.push({
      unitId: unit.id,
      costCategoryKey: "heizung",
      allocationKeyUsed: "consumption",
      totalPropertyCostCents: verbrauchCents,
      unitShareCents: unitShare,
      // A vacant unit that used no heat correctly gets 0 here already via
      // 0 metered consumption - there's no separate "vacancy" bucket for
      // the consumption-based portion (see doc comment above).
      vacancyShareCents: 0,
      daysOccupied: grund.daysOccupied,
      daysTotal,
      isEstimated: resolvedUnit?.isEstimated ?? false,
      estimationMethod: resolvedUnit?.method ?? null,
      basisNumerator: resolvedUnit?.value ?? null,
      basisDenominator: totalConsumption > 0 ? totalConsumption : null,
      externalProviderName: null,
    });
  }
  return lines;
}

/** 100%-by-resolved-consumption allocation (real metered value or §9a substitute), e.g. for Wasser/Abwasser, scoped to a circuit's member units. */
function computeConsumptionLines(
  costCategoryKey: string,
  totalCents: number,
  circuitUnits: CalcUnit[],
  leaseSegments: CalcLeaseSegment[],
  consumption: CalcConsumptionByUnit[],
  periodStart: string,
  periodEnd: string,
): StatementLineResult[] {
  const daysTotal = daysBetweenInclusive(periodStart, periodEnd);
  const occupiedDaysByUnit = new Map(
    computeUnitDayWeights("units", circuitUnits, leaseSegments, periodStart, periodEnd).map((w) => [w.unitId, w.daysOccupied]),
  );

  const consumptionInputs = buildConsumptionInputs(
    circuitUnits,
    consumption,
    (c) => (c.coldWater === null && c.hotWater === null ? null : (c.coldWater ?? 0) + (c.hotWater ?? 0)),
    (c) => (c.priorColdWater === null && c.priorHotWater === null ? null : (c.priorColdWater ?? 0) + (c.priorHotWater ?? 0)),
  );
  const resolved = resolveCircuitConsumption(consumptionInputs);
  const resolvedByUnit = new Map(resolved.map((r) => [r.unitId, r]));
  const totalConsumption = resolved.reduce((sum, r) => sum + r.value, 0);

  return circuitUnits.map((unit) => {
    const resolvedUnit = resolvedByUnit.get(unit.id);
    const unitShareCents = totalConsumption > 0 && resolvedUnit ? roundCents((totalCents * resolvedUnit.value) / totalConsumption) : 0;
    return {
      unitId: unit.id,
      costCategoryKey,
      allocationKeyUsed: "consumption" as const,
      totalPropertyCostCents: totalCents,
      unitShareCents,
      vacancyShareCents: 0,
      daysOccupied: occupiedDaysByUnit.get(unit.id) ?? 0,
      daysTotal,
      isEstimated: resolvedUnit?.isEstimated ?? false,
      estimationMethod: resolvedUnit?.method ?? null,
      basisNumerator: resolvedUnit?.value ?? null,
      basisDenominator: totalConsumption > 0 ? totalConsumption : null,
      externalProviderName: null,
    };
  });
}

/**
 * `fixed_manual`-overridden receipts bypass the whole allocation-key
 * machinery: each receipt's full amount is charged only to its
 * `targetUnitId`. Receipts missing a `targetUnitId` fall back to an even
 * split across the receipt's own circuit's member units (a lenient default
 * rather than silently dropping the cost) - callers should validate
 * `targetUnitId` is set at receipt-intake time to avoid relying on this
 * fallback.
 */
function computeFixedManualLines(
  receipts: CalcReceipt[],
  costCircuits: CalcCostCircuit[],
  units: CalcUnit[],
  periodStart: string,
  periodEnd: string,
): StatementLineResult[] {
  const daysTotal = daysBetweenInclusive(periodStart, periodEnd);
  const allUnitsById = unitsById(units);
  const circuitsById = new Map(costCircuits.map((c) => [c.id, c]));
  const overridden = receipts.filter((r) => r.allocationKeyOverride === "fixed_manual");
  const lines: StatementLineResult[] = [];
  for (const receipt of overridden) {
    if (receipt.targetUnitId) {
      lines.push({
        unitId: receipt.targetUnitId,
        costCategoryKey: receipt.costCategoryKey,
        allocationKeyUsed: "fixed_manual",
        totalPropertyCostCents: receipt.amountCents,
        unitShareCents: receipt.amountCents,
        vacancyShareCents: 0,
        daysOccupied: daysTotal,
        daysTotal,
        isEstimated: false,
        estimationMethod: null,
        basisNumerator: null,
        basisDenominator: null,
        externalProviderName: null,
      });
      continue;
    }
    const circuitUnitIds = circuitsById.get(receipt.costCircuitId)?.unitIds ?? [];
    const circuitUnits = circuitUnitIds.map((id) => allUnitsById.get(id)).filter((u): u is CalcUnit => !!u);
    if (circuitUnits.length > 0) {
      const perUnit = roundCents(receipt.amountCents / circuitUnits.length);
      for (const unit of circuitUnits) {
        lines.push({
          unitId: unit.id,
          costCategoryKey: receipt.costCategoryKey,
          allocationKeyUsed: "fixed_manual",
          totalPropertyCostCents: receipt.amountCents,
          unitShareCents: perUnit,
          vacancyShareCents: 0,
          daysOccupied: daysTotal,
          daysTotal,
          isEstimated: false,
          estimationMethod: null,
          basisNumerator: null,
          basisDenominator: null,
          externalProviderName: null,
        });
      }
    }
  }
  return lines;
}

/**
 * (circuit, category) pairs opted into `external_provider` billing (see
 * migrations/0012) skip the whole allocation-key pipeline entirely - instead
 * each unit's cost is the landlord's own transcribed external-provider
 * amount (see CalcExternalAllocation), summed across any allocation rows
 * whose PROVIDER period overlaps the statement period, pro-rated by
 * day-overlap when a row only partially overlaps (the common case is an
 * exact period match, where the proration factor is simply 1 - see the
 * module brief's "don't over-engineer" note on this). There is no "vacancy"
 * concept here - a unit's external total is charged in full, then split
 * across its own lease segments' occupied days by the shared downstream
 * logic in computeTenantSummaries, exactly like every other allocation key.
 */
function computeExternalProviderLines(
  settings: CalcCircuitCategorySetting[],
  externalAllocations: CalcExternalAllocation[],
  costCircuits: CalcCostCircuit[],
  units: CalcUnit[],
  periodStart: string,
  periodEnd: string,
): StatementLineResult[] {
  const daysTotal = daysBetweenInclusive(periodStart, periodEnd);
  const allUnitsById = unitsById(units);
  const circuitsById = new Map(costCircuits.map((c) => [c.id, c]));
  const externalSettings = settings.filter((s) => s.billingMode === "external_provider");
  const lines: StatementLineResult[] = [];

  for (const setting of externalSettings) {
    const circuitUnitIds = circuitsById.get(setting.costCircuitId)?.unitIds ?? [];
    const circuitUnits = circuitUnitIds.map((id) => allUnitsById.get(id)).filter((u): u is CalcUnit => !!u);
    const relevantAllocations = externalAllocations.filter(
      (a) => a.costCircuitId === setting.costCircuitId && a.costCategoryKey === setting.costCategoryKey,
    );

    const totalsByUnit = new Map<string, number>();
    for (const allocation of relevantAllocations) {
      const overlap = clampDateRange(allocation.periodStart, allocation.periodEnd, periodStart, periodEnd);
      if (!overlap) continue; // this provider period doesn't touch the statement period at all
      const overlapDays = daysBetweenInclusive(overlap.start, overlap.end);
      const providerPeriodDays = daysBetweenInclusive(allocation.periodStart, allocation.periodEnd);
      const fraction = providerPeriodDays > 0 ? overlapDays / providerPeriodDays : 0;
      const prorated = roundCents(allocation.amountCents * fraction);
      totalsByUnit.set(allocation.unitId, (totalsByUnit.get(allocation.unitId) ?? 0) + prorated);
    }

    const poolTotalCents = Array.from(totalsByUnit.values()).reduce((sum, v) => sum + v, 0);

    for (const unit of circuitUnits) {
      lines.push({
        unitId: unit.id,
        costCategoryKey: setting.costCategoryKey,
        allocationKeyUsed: "external_provider",
        totalPropertyCostCents: poolTotalCents,
        unitShareCents: totalsByUnit.get(unit.id) ?? 0,
        vacancyShareCents: 0,
        daysOccupied: daysTotal,
        daysTotal,
        isEstimated: false,
        estimationMethod: null,
        basisNumerator: null,
        basisDenominator: null,
        externalProviderName: setting.providerName,
      });
    }
  }
  return lines;
}

/** Full per-unit/per-category statement line breakdown for a property + period, grouped per (cost circuit, category). */
export function computeStatementLines(input: StatementCalculationInput): StatementLineResult[] {
  const {
    periodStart,
    periodEnd,
    units,
    costCircuits,
    leaseSegments,
    receipts,
    consumption,
    heatingConsumptionSharePercent,
    circuitCategorySettings,
    externalAllocations,
  } = input;
  const externalModePairs = new Set(
    circuitCategorySettings.filter((s) => s.billingMode === "external_provider").map((s) => circuitCategoryKey(s.costCircuitId, s.costCategoryKey)),
  );
  const buckets = computeCategoryTotals(receipts, externalModePairs);
  const lines: StatementLineResult[] = [];
  const allUnitsById = unitsById(units);
  const circuitsById = new Map(costCircuits.map((c) => [c.id, c]));

  for (const bucket of buckets.values()) {
    const circuit = circuitsById.get(bucket.costCircuitId);
    const circuitUnits = (circuit?.unitIds ?? []).map((id) => allUnitsById.get(id)).filter((u): u is CalcUnit => !!u);
    const circuitUnitIdSet = new Set(circuitUnits.map((u) => u.id));
    const circuitLeaseSegments = leaseSegments.filter((s) => circuitUnitIdSet.has(s.unitId));

    if (bucket.costCategoryKey === "heizung" && bucket.allocationKey === "consumption") {
      lines.push(
        ...computeHeatingLines(bucket.totalCents, circuitUnits, circuitLeaseSegments, consumption, periodStart, periodEnd, heatingConsumptionSharePercent),
      );
      continue;
    }
    if (bucket.allocationKey === "consumption") {
      lines.push(...computeConsumptionLines(bucket.costCategoryKey, bucket.totalCents, circuitUnits, circuitLeaseSegments, consumption, periodStart, periodEnd));
      continue;
    }
    if (bucket.allocationKey === "fixed_manual") continue; // never reached - computeCategoryTotals excludes these
    if (bucket.allocationKey === "external_provider") continue; // never reached - receipts never carry this override, only circuit/category settings do
    const shares = allocateByDayWeights(bucket.allocationKey, bucket.totalCents, circuitUnits, circuitLeaseSegments, periodStart, periodEnd);
    const daysTotal = daysBetweenInclusive(periodStart, periodEnd);
    for (const share of shares) {
      lines.push({
        unitId: share.unitId,
        costCategoryKey: bucket.costCategoryKey,
        allocationKeyUsed: bucket.allocationKey,
        totalPropertyCostCents: bucket.totalCents,
        unitShareCents: share.unitShareCents,
        vacancyShareCents: share.vacancyShareCents,
        daysOccupied: share.daysOccupied,
        daysTotal,
        isEstimated: false,
        estimationMethod: null,
        basisNumerator: share.basisNumerator,
        basisDenominator: share.basisDenominator,
        externalProviderName: null,
      });
    }
  }

  lines.push(...computeFixedManualLines(receipts, costCircuits, units, periodStart, periodEnd));
  lines.push(...computeExternalProviderLines(circuitCategorySettings, externalAllocations, costCircuits, units, periodStart, periodEnd));
  return lines;
}

/**
 * Rolls per-unit statement lines up into one summary per lease-segment
 * (handles a mid-period Mieterwechsel producing two summaries for the same
 * unit) - just the allocated-cost side. Prepayments/balance are attached by
 * the caller (statements.ts), which prefers actual `vermieter_rent_payments`
 * rows and falls back to contractual nk_prepayment_cents × months-covered
 * when payment records don't fully cover the segment - see that module's
 * `computePrepaymentsForSegment` for that logic; it's deliberately kept out
 * of this otherwise-pure engine since it depends on DB reads.
 */
export function computeTenantSummaries(lines: StatementLineResult[], leaseSegments: CalcLeaseSegment[]): TenantSummaryResult[] {
  const costByUnit = new Map<string, number>();
  for (const line of lines) {
    costByUnit.set(line.unitId, (costByUnit.get(line.unitId) ?? 0) + line.unitShareCents);
  }

  // Multiple lease segments can share a unit (Mieterwechsel); split the
  // unit's total allocated cost across its segments proportional to each
  // segment's occupied day count, since statement_lines only track cost per
  // unit, not per lease-segment.
  const segmentsByUnit = new Map<string, CalcLeaseSegment[]>();
  for (const segment of leaseSegments) {
    const list = segmentsByUnit.get(segment.unitId) ?? [];
    list.push(segment);
    segmentsByUnit.set(segment.unitId, list);
  }

  const summaries: TenantSummaryResult[] = [];
  for (const [unitId, segments] of segmentsByUnit) {
    const unitCost = costByUnit.get(unitId) ?? 0;
    const totalDays = segments.reduce((sum, s) => sum + daysBetweenInclusive(s.segmentStart, s.segmentEnd), 0);
    for (const segment of segments) {
      const segmentDays = daysBetweenInclusive(segment.segmentStart, segment.segmentEnd);
      const allocatedCost = totalDays > 0 ? roundCents((unitCost * segmentDays) / totalDays) : 0;
      summaries.push({
        unitId,
        leaseId: segment.leaseId,
        segmentStart: segment.segmentStart,
        segmentEnd: segment.segmentEnd,
        totalAllocatedCostCents: allocatedCost,
      });
    }
  }
  return summaries;
}

/**
 * Re-derives one lease-segment's own view of a unit's statement lines, for
 * a unit covered by more than one lease segment within the period
 * (Mieterwechsel). `computeStatementLines` tracks cost per UNIT only, not
 * per lease-segment - every `StatementLineResult`/`StatementLineDto` for
 * that unit carries the *whole unit's* full-period `unitShareCents` and
 * `daysOccupied`, identical for every tenant who occupied it. Rendering
 * those unit-level numbers verbatim on an individual tenant's statement
 * page would show every co-tenant of that unit the SAME full-unit amount
 * and day-count (e.g. both halves of a mid-year Mieterwechsel each seeing
 * the full year's Kopfteil share), contradicting the correctly
 * day-prorated total in `computeTenantSummaries`'s
 * `TenantSummaryResult.totalAllocatedCostCents` - see pdf/render.ts's
 * per-tenant table and pdf/explanationText.ts's per-tenant paragraph, both
 * of which call this before rendering so the itemized lines and the
 * reconciliation total stay mutually consistent for that tenant. Prorates
 * each line's `unitShareCents` by this segment's own day-count over the
 * sum of all of the unit's segment day-counts in the period - the same
 * ratio `computeTenantSummaries` applies to the unit's *aggregate* cost,
 * just applied per line here so the itemized table/explanation tie out
 * too. `vacancyShareCents` is zeroed (vacancy is never a tenant's charge)
 * and `daysOccupied` becomes this segment's own days rather than the
 * unit's total. A single-segment unit is returned unchanged (ratio is
 * exactly 1 - no proration needed, and no rounding drift introduced).
 */
export function proratedLinesForSegment<T extends { unitShareCents: number; vacancyShareCents: number; daysOccupied: number }>(
  unitLines: T[],
  segmentStart: string,
  segmentEnd: string,
  allUnitSegmentDayRanges: { start: string; end: string }[],
): T[] {
  if (allUnitSegmentDayRanges.length <= 1) return unitLines;
  const segmentDays = daysBetweenInclusive(segmentStart, segmentEnd);
  const totalDays = allUnitSegmentDayRanges.reduce((sum, r) => sum + daysBetweenInclusive(r.start, r.end), 0);
  if (totalDays <= 0) return unitLines;
  return unitLines.map((line) => ({
    ...line,
    unitShareCents: roundCents((line.unitShareCents * segmentDays) / totalDays),
    vacancyShareCents: 0,
    daysOccupied: segmentDays,
  }));
}

export { daysBetweenInclusive, clampDateRange };
