import type { VermieterAllocationKey, VermieterEstimationMethod } from "../db/types.js";
import { getCostCategory } from "../db/costCategories.js";
import { resolveCircuitConsumption, type UnitConsumptionInput } from "./meterSubstitute.js";

/**
 * Pure calculation engine for a Nebenkostenabrechnung (§556 BGB operating-
 * cost statement). Everything here is deliberately side-effect-free and
 * takes plain in-memory data - `services/statements.ts` is the only caller,
 * and does all the SQLite reads/writes around it. Kept pure so the
 * allocation math (which ends up on a document a tenant can legally
 * dispute) can be reasoned about/tested in isolation from storage.
 *
 * A statement is a point-in-time legal snapshot - once generated its
 * `vermieter_statement_lines`/`vermieter_statement_tenant_summaries` rows
 * are never recomputed live, only re-generated by running this engine again
 * (see statements.ts).
 *
 * Cost circuits (Abrechnungskreise): every receipt belongs to a circuit
 * (`CalcReceipt.costCircuitId`), and a circuit only spans a subset of a
 * property's units (`CalcCostCircuit.unitIds`) - e.g. units with their own
 * electric Durchlauferhitzer simply aren't members of the
 * Zentralheizung/Warmwasser circuit, so they're excluded from both the cost
 * pool and its participant/denominator set entirely. Grouping is now
 * per-(circuit, category) rather than per-(property, category); everything
 * else (day-proration, vacancy-to-landlord bucket, the HeizkostenV 70/30
 * split) is unchanged in spirit, just re-scoped to a circuit's unit list
 * instead of the whole property's.
 */

export interface CalcUnit {
  id: string;
  sizeSqm: number;
}

/** A property's Abrechnungskreis (cost circuit) - see the module-level doc comment above. */
export interface CalcCostCircuit {
  id: string;
  unitIds: string[];
}

/** One lease's coverage of a unit, clipped to the statement period. `personCount` is simply the number of tenants linked to the lease (see services/tenants.ts::listTenantsForLease) - the spec's agreed simplification for a "Personenzahl" headcount rather than a separate occupant-count field. */
export interface CalcLeaseSegment {
  leaseId: string;
  unitId: string;
  /** Clipped to the statement period - always >= periodStart and <= periodEnd. */
  segmentStart: string;
  segmentEnd: string;
  personCount: number;
}

export interface CalcReceipt {
  id: string;
  costCategoryKey: string;
  amountCents: number;
  allocationKeyOverride: VermieterAllocationKey | null;
  targetUnitId: string | null;
  /** Which Abrechnungskreis this receipt's cost pool belongs to - always a concrete circuit id (services/receipts.ts resolves the property's default circuit when none was given). */
  costCircuitId: string;
}

/**
 * Per-unit metered consumption within the period, keyed by the meter's
 * `type` (see services/meters.ts::consumptionInPeriod, summed across all
 * meters of that type in the unit). `null` means "no meter, or no reading
 * pair bracketing the period" - distinct from a real `0`, since it drives
 * the §9a HeizkostenV substitute-value resolution (services/
 * meterSubstitute.ts) rather than being silently treated as zero
 * consumption. `prior*` fields are the same unit's own metered consumption
 * in the prior comparable period (see services/meters.ts::
 * priorComparablePeriod), used for the "own history" substitute branch.
 */
export interface CalcConsumptionByUnit {
  unitId: string;
  heating: number | null;
  coldWater: number | null;
  hotWater: number | null;
  priorHeating: number | null;
  priorColdWater: number | null;
  priorHotWater: number | null;
}

export interface StatementLineResult {
  unitId: string;
  costCategoryKey: string;
  allocationKeyUsed: VermieterAllocationKey;
  totalPropertyCostCents: number;
  unitShareCents: number;
  vacancyShareCents: number;
  daysOccupied: number;
  daysTotal: number;
  /** True when unitShareCents was derived from a §9a HeizkostenV substitute value rather than a real meter reading. Always false for non-consumption allocation keys. */
  isEstimated: boolean;
  /** 'metered' | one of the substitute methods for consumption-based lines; null for every other allocation key. */
  estimationMethod: VermieterEstimationMethod | null;
}

export interface TenantSummaryResult {
  unitId: string;
  leaseId: string;
  segmentStart: string;
  segmentEnd: string;
  totalAllocatedCostCents: number;
}

export interface StatementCalculationInput {
  periodStart: string; // YYYY-MM-DD
  periodEnd: string; // YYYY-MM-DD
  units: CalcUnit[];
  costCircuits: CalcCostCircuit[];
  leaseSegments: CalcLeaseSegment[];
  receipts: CalcReceipt[];
  consumption: CalcConsumptionByUnit[];
  /** Verbrauchskosten share of Heizung costs, 0-100. HeizkostenV §7 mandates at least 50%, standard/default 70. The remaining share is Grundkosten, allocated by qm. */
  heatingConsumptionSharePercent: number;
}

export interface StatementCalculationResult {
  lines: StatementLineResult[];
  tenantSummaries: TenantSummaryResult[];
}

function daysBetweenInclusive(startIso: string, endIso: string): number {
  const start = new Date(`${startIso}T00:00:00Z`).getTime();
  const end = new Date(`${endIso}T00:00:00Z`).getTime();
  return Math.max(0, Math.round((end - start) / 86_400_000) + 1);
}

function clampDateRange(aStart: string, aEnd: string, bStart: string, bEnd: string): { start: string; end: string } | null {
  const start = aStart > bStart ? aStart : bStart;
  const end = aEnd < bEnd ? aEnd : bEnd;
  if (start > end) return null;
  return { start, end };
}

function roundCents(value: number): number {
  return Math.round(value);
}

interface CategoryBucket {
  costCircuitId: string;
  costCategoryKey: string;
  allocationKey: VermieterAllocationKey;
  totalCents: number;
}

/**
 * Groups receipts (excluding `fixed_manual`-overridden ones, which bypass
 * this entirely - see computeFixedManualLines) into per-(circuit, category,
 * effective allocation key) cost buckets. A category can appear in more than
 * one bucket for the same circuit if some of its receipts were individually
 * overridden to a different allocation key, or if it has receipts in more
 * than one circuit.
 */
export function computeCategoryTotals(receipts: CalcReceipt[]): Map<string, CategoryBucket> {
  const buckets = new Map<string, CategoryBucket>();
  for (const receipt of receipts) {
    if (receipt.allocationKeyOverride === "fixed_manual") continue; // handled separately, per-receipt
    const category = getCostCategory(receipt.costCategoryKey);
    const allocationKey = receipt.allocationKeyOverride ?? category?.defaultAllocationKey ?? "sqm";
    const bucketKey = `${receipt.costCircuitId}::${receipt.costCategoryKey}::${allocationKey}`;
    const bucket = buckets.get(bucketKey);
    if (bucket) bucket.totalCents += receipt.amountCents;
    else buckets.set(bucketKey, { costCircuitId: receipt.costCircuitId, costCategoryKey: receipt.costCategoryKey, allocationKey, totalCents: receipt.amountCents });
  }
  return buckets;
}

interface UnitDayWeights {
  unitId: string;
  /** Sum over this unit's lease segments of (segment weight * segment days). */
  occupiedWeightDays: number;
  /** (daysTotal - daysOccupied) * referenceWeight - the weight-days attributable to no tenant at all. */
  vacancyWeightDays: number;
  daysOccupied: number;
  /** The single occupying lease's segment, when there's exactly one covering the whole occupied span - used to attribute a statement_line's `lease_id`. Mid-period tenant changes (>1 segment) leave this null; the per-tenant breakdown for those still comes from tenantSummaries. */
  soleLeaseId: string | null;
}

/**
 * Computes, for each unit, how many "weight-days" it contributed within the
 * period under a day-proration model shared by the sqm/persons/units
 * allocation bases: each day of the period a unit is under lease
 * contributes `segmentWeight(basis, segment)`; each day it's vacant
 * contributes `referenceWeight(basis, unit)` to a *landlord-borne* vacancy
 * bucket instead of being redistributed to other units (see the module's
 * top-level spec: vacancy is never picked up by other tenants). For the
 * `sqm`/`units` bases the reference weight always equals the occupied
 * weight (a unit's size or "1" doesn't change with occupancy), so this
 * reduces exactly to "cost per weight-day, split into occupied/vacant by
 * day count" as specified. For `persons` there's no natural capacity for a
 * vacant unit, so the reference weight falls back to the unit's own last
 * known headcount within the period (or 1 if it was never occupied during
 * the period) - a documented simplification. `units` here is always the
 * circuit's member units, not necessarily the whole property.
 */
function computeUnitDayWeights(
  basis: "sqm" | "persons" | "units",
  units: CalcUnit[],
  leaseSegments: CalcLeaseSegment[],
  periodStart: string,
  periodEnd: string,
): UnitDayWeights[] {
  const daysTotal = daysBetweenInclusive(periodStart, periodEnd);

  return units.map((unit) => {
    const segments = leaseSegments.filter((s) => s.unitId === unit.id);
    let occupiedWeightDays = 0;
    let daysOccupied = 0;
    let lastPersonCount = 1;
    for (const segment of segments) {
      const clipped = clampDateRange(segment.segmentStart, segment.segmentEnd, periodStart, periodEnd);
      if (!clipped) continue;
      const segmentDays = daysBetweenInclusive(clipped.start, clipped.end);
      const weight = basis === "sqm" ? unit.sizeSqm : basis === "units" ? 1 : Math.max(1, segment.personCount);
      occupiedWeightDays += weight * segmentDays;
      daysOccupied += segmentDays;
      lastPersonCount = Math.max(1, segment.personCount);
    }
    const vacancyDays = Math.max(0, daysTotal - daysOccupied);
    const referenceWeight = basis === "sqm" ? unit.sizeSqm : basis === "units" ? 1 : lastPersonCount;
    const vacancyWeightDays = referenceWeight * vacancyDays;
    const soleLeaseId = segments.length === 1 ? (segments[0]?.leaseId ?? null) : null;

    return { unitId: unit.id, occupiedWeightDays, vacancyWeightDays, daysOccupied, soleLeaseId };
  });
}

/** Allocates `totalCents` across `units` (a circuit's member units) for one of the day-prorated bases (sqm/persons/units). */
function allocateByDayWeights(
  basis: "sqm" | "persons" | "units",
  totalCents: number,
  units: CalcUnit[],
  leaseSegments: CalcLeaseSegment[],
  periodStart: string,
  periodEnd: string,
): { unitId: string; unitShareCents: number; vacancyShareCents: number; daysOccupied: number }[] {
  const weights = computeUnitDayWeights(basis, units, leaseSegments, periodStart, periodEnd);
  const totalWeightDays = weights.reduce((sum, w) => sum + w.occupiedWeightDays + w.vacancyWeightDays, 0);
  if (totalWeightDays <= 0) {
    return weights.map((w) => ({ unitId: w.unitId, unitShareCents: 0, vacancyShareCents: 0, daysOccupied: w.daysOccupied }));
  }
  return weights.map((w) => ({
    unitId: w.unitId,
    unitShareCents: roundCents((totalCents * w.occupiedWeightDays) / totalWeightDays),
    vacancyShareCents: roundCents((totalCents * w.vacancyWeightDays) / totalWeightDays),
    daysOccupied: w.daysOccupied,
  }));
}

function unitsById(units: CalcUnit[]): Map<string, CalcUnit> {
  return new Map(units.map((u) => [u.id, u]));
}

/** Builds the §9a HeizkostenV resolver input for one meter kind, scoped to a circuit's member units. */
function buildConsumptionInputs(
  circuitUnits: CalcUnit[],
  consumption: CalcConsumptionByUnit[],
  pick: (c: CalcConsumptionByUnit) => number | null,
  pickPrior: (c: CalcConsumptionByUnit) => number | null,
): UnitConsumptionInput[] {
  const byUnit = new Map(consumption.map((c) => [c.unitId, c]));
  return circuitUnits.map((unit) => {
    const entry = byUnit.get(unit.id);
    return {
      unitId: unit.id,
      sizeSqm: unit.sizeSqm,
      currentPeriodValue: entry ? pick(entry) : null,
      priorPeriodValue: entry ? pickPrior(entry) : null,
    };
  });
}

/**
 * Heizkostenverordnung §7: heating costs must be split into a
 * consumption-independent "Grundkosten" portion (allocated like a normal
 * qm-based cost) and a consumption-dependent "Verbrauchskosten" portion
 * (allocated by each unit's resolved heat consumption - real metered value
 * or, per §9a, a substitute - see services/meterSubstitute.ts), with the
 * consumption portion required to be 50-70% - 70/30 is the statutory
 * standard split absent a differing agreement, hence the default here.
 * Both portions are scoped to `circuitUnits` (the circuit's member units),
 * not necessarily the whole property. Water/electricity `consumption`-key
 * categories skip this split entirely and allocate 100% by resolved
 * consumption (see computeConsumptionLines).
 */
function computeHeatingLines(
  totalCents: number,
  circuitUnits: CalcUnit[],
  leaseSegments: CalcLeaseSegment[],
  consumption: CalcConsumptionByUnit[],
  periodStart: string,
  periodEnd: string,
  consumptionSharePercent: number,
): StatementLineResult[] {
  const daysTotal = daysBetweenInclusive(periodStart, periodEnd);
  const verbrauchCents = roundCents((totalCents * consumptionSharePercent) / 100);
  const grundCents = totalCents - verbrauchCents;

  const grundShares = allocateByDayWeights("sqm", grundCents, circuitUnits, leaseSegments, periodStart, periodEnd);

  const consumptionInputs = buildConsumptionInputs(
    circuitUnits,
    consumption,
    (c) => c.heating,
    (c) => c.priorHeating,
  );
  const resolved = resolveCircuitConsumption(consumptionInputs);
  const resolvedByUnit = new Map(resolved.map((r) => [r.unitId, r]));
  const totalConsumption = resolved.reduce((sum, r) => sum + r.value, 0);

  const lines: StatementLineResult[] = [];
  for (const unit of circuitUnits) {
    const grund = grundShares.find((g) => g.unitId === unit.id)!;
    lines.push({
      unitId: unit.id,
      costCategoryKey: "heizung",
      allocationKeyUsed: "sqm",
      totalPropertyCostCents: grundCents,
      unitShareCents: grund.unitShareCents,
      vacancyShareCents: grund.vacancyShareCents,
      daysOccupied: grund.daysOccupied,
      daysTotal,
      isEstimated: false,
      estimationMethod: null,
    });

    // Verbrauchskosten: proportional to each unit's resolved consumption
    // (real metered value or §9a substitute). If nobody in the circuit has
    // any consumption data at all (totalConsumption <= 0 even after
    // substitution - shouldn't normally happen once the sqm-fallback branch
    // kicks in, but guards an empty-circuit edge case), the cost is simply
    // left unallocated/0 rather than guessed.
    const resolvedUnit = resolvedByUnit.get(unit.id);
    const unitShare = totalConsumption > 0 && resolvedUnit ? roundCents((verbrauchCents * resolvedUnit.value) / totalConsumption) : 0;
    lines.push({
      unitId: unit.id,
      costCategoryKey: "heizung",
      allocationKeyUsed: "consumption",
      totalPropertyCostCents: verbrauchCents,
      unitShareCents: unitShare,
      // A vacant unit that used no heat correctly gets 0 here already via
      // 0 metered consumption - there's no separate "vacancy" bucket for
      // the consumption-based portion (see doc comment above).
      vacancyShareCents: 0,
      daysOccupied: grund.daysOccupied,
      daysTotal,
      isEstimated: resolvedUnit?.isEstimated ?? false,
      estimationMethod: resolvedUnit?.method ?? null,
    });
  }
  return lines;
}

/** 100%-by-resolved-consumption allocation (real metered value or §9a substitute), e.g. for Wasser/Abwasser, scoped to a circuit's member units. */
function computeConsumptionLines(
  costCategoryKey: string,
  totalCents: number,
  circuitUnits: CalcUnit[],
  leaseSegments: CalcLeaseSegment[],
  consumption: CalcConsumptionByUnit[],
  periodStart: string,
  periodEnd: string,
): StatementLineResult[] {
  const daysTotal = daysBetweenInclusive(periodStart, periodEnd);
  const occupiedDaysByUnit = new Map(
    computeUnitDayWeights("units", circuitUnits, leaseSegments, periodStart, periodEnd).map((w) => [w.unitId, w.daysOccupied]),
  );

  const consumptionInputs = buildConsumptionInputs(
    circuitUnits,
    consumption,
    (c) => (c.coldWater === null && c.hotWater === null ? null : (c.coldWater ?? 0) + (c.hotWater ?? 0)),
    (c) => (c.priorColdWater === null && c.priorHotWater === null ? null : (c.priorColdWater ?? 0) + (c.priorHotWater ?? 0)),
  );
  const resolved = resolveCircuitConsumption(consumptionInputs);
  const resolvedByUnit = new Map(resolved.map((r) => [r.unitId, r]));
  const totalConsumption = resolved.reduce((sum, r) => sum + r.value, 0);

  return circuitUnits.map((unit) => {
    const resolvedUnit = resolvedByUnit.get(unit.id);
    const unitShareCents = totalConsumption > 0 && resolvedUnit ? roundCents((totalCents * resolvedUnit.value) / totalConsumption) : 0;
    return {
      unitId: unit.id,
      costCategoryKey,
      allocationKeyUsed: "consumption" as const,
      totalPropertyCostCents: totalCents,
      unitShareCents,
      vacancyShareCents: 0,
      daysOccupied: occupiedDaysByUnit.get(unit.id) ?? 0,
      daysTotal,
      isEstimated: resolvedUnit?.isEstimated ?? false,
      estimationMethod: resolvedUnit?.method ?? null,
    };
  });
}

/**
 * `fixed_manual`-overridden receipts bypass the whole allocation-key
 * machinery: each receipt's full amount is charged only to its
 * `targetUnitId`. Receipts missing a `targetUnitId` fall back to an even
 * split across the receipt's own circuit's member units (a lenient default
 * rather than silently dropping the cost) - callers should validate
 * `targetUnitId` is set at receipt-intake time to avoid relying on this
 * fallback.
 */
function computeFixedManualLines(
  receipts: CalcReceipt[],
  costCircuits: CalcCostCircuit[],
  units: CalcUnit[],
  periodStart: string,
  periodEnd: string,
): StatementLineResult[] {
  const daysTotal = daysBetweenInclusive(periodStart, periodEnd);
  const allUnitsById = unitsById(units);
  const circuitsById = new Map(costCircuits.map((c) => [c.id, c]));
  const overridden = receipts.filter((r) => r.allocationKeyOverride === "fixed_manual");
  const lines: StatementLineResult[] = [];
  for (const receipt of overridden) {
    if (receipt.targetUnitId) {
      lines.push({
        unitId: receipt.targetUnitId,
        costCategoryKey: receipt.costCategoryKey,
        allocationKeyUsed: "fixed_manual",
        totalPropertyCostCents: receipt.amountCents,
        unitShareCents: receipt.amountCents,
        vacancyShareCents: 0,
        daysOccupied: daysTotal,
        daysTotal,
        isEstimated: false,
        estimationMethod: null,
      });
      continue;
    }
    const circuitUnitIds = circuitsById.get(receipt.costCircuitId)?.unitIds ?? [];
    const circuitUnits = circuitUnitIds.map((id) => allUnitsById.get(id)).filter((u): u is CalcUnit => !!u);
    if (circuitUnits.length > 0) {
      const perUnit = roundCents(receipt.amountCents / circuitUnits.length);
      for (const unit of circuitUnits) {
        lines.push({
          unitId: unit.id,
          costCategoryKey: receipt.costCategoryKey,
          allocationKeyUsed: "fixed_manual",
          totalPropertyCostCents: receipt.amountCents,
          unitShareCents: perUnit,
          vacancyShareCents: 0,
          daysOccupied: daysTotal,
          daysTotal,
          isEstimated: false,
          estimationMethod: null,
        });
      }
    }
  }
  return lines;
}

/** Full per-unit/per-category statement line breakdown for a property + period, grouped per (cost circuit, category). */
export function computeStatementLines(input: StatementCalculationInput): StatementLineResult[] {
  const { periodStart, periodEnd, units, costCircuits, leaseSegments, receipts, consumption, heatingConsumptionSharePercent } = input;
  const buckets = computeCategoryTotals(receipts);
  const lines: StatementLineResult[] = [];
  const allUnitsById = unitsById(units);
  const circuitsById = new Map(costCircuits.map((c) => [c.id, c]));

  for (const bucket of buckets.values()) {
    const circuit = circuitsById.get(bucket.costCircuitId);
    const circuitUnits = (circuit?.unitIds ?? []).map((id) => allUnitsById.get(id)).filter((u): u is CalcUnit => !!u);
    const circuitUnitIdSet = new Set(circuitUnits.map((u) => u.id));
    const circuitLeaseSegments = leaseSegments.filter((s) => circuitUnitIdSet.has(s.unitId));

    if (bucket.costCategoryKey === "heizung" && bucket.allocationKey === "consumption") {
      lines.push(
        ...computeHeatingLines(bucket.totalCents, circuitUnits, circuitLeaseSegments, consumption, periodStart, periodEnd, heatingConsumptionSharePercent),
      );
      continue;
    }
    if (bucket.allocationKey === "consumption") {
      lines.push(...computeConsumptionLines(bucket.costCategoryKey, bucket.totalCents, circuitUnits, circuitLeaseSegments, consumption, periodStart, periodEnd));
      continue;
    }
    if (bucket.allocationKey === "fixed_manual") continue; // never reached - computeCategoryTotals excludes these
    const shares = allocateByDayWeights(bucket.allocationKey, bucket.totalCents, circuitUnits, circuitLeaseSegments, periodStart, periodEnd);
    const daysTotal = daysBetweenInclusive(periodStart, periodEnd);
    for (const share of shares) {
      lines.push({
        unitId: share.unitId,
        costCategoryKey: bucket.costCategoryKey,
        allocationKeyUsed: bucket.allocationKey,
        totalPropertyCostCents: bucket.totalCents,
        unitShareCents: share.unitShareCents,
        vacancyShareCents: share.vacancyShareCents,
        daysOccupied: share.daysOccupied,
        daysTotal,
        isEstimated: false,
        estimationMethod: null,
      });
    }
  }

  lines.push(...computeFixedManualLines(receipts, costCircuits, units, periodStart, periodEnd));
  return lines;
}

/**
 * Rolls per-unit statement lines up into one summary per lease-segment
 * (handles a mid-period Mieterwechsel producing two summaries for the same
 * unit) - just the allocated-cost side. Prepayments/balance are attached by
 * the caller (statements.ts), which prefers actual `vermieter_rent_payments`
 * rows and falls back to contractual nk_prepayment_cents × months-covered
 * when payment records don't fully cover the segment - see that module's
 * `computePrepaymentsForSegment` for that logic; it's deliberately kept out
 * of this otherwise-pure engine since it depends on DB reads.
 */
export function computeTenantSummaries(lines: StatementLineResult[], leaseSegments: CalcLeaseSegment[]): TenantSummaryResult[] {
  const costByUnit = new Map<string, number>();
  for (const line of lines) {
    costByUnit.set(line.unitId, (costByUnit.get(line.unitId) ?? 0) + line.unitShareCents);
  }

  // Multiple lease segments can share a unit (Mieterwechsel); split the
  // unit's total allocated cost across its segments proportional to each
  // segment's occupied day count, since statement_lines only track cost per
  // unit, not per lease-segment.
  const segmentsByUnit = new Map<string, CalcLeaseSegment[]>();
  for (const segment of leaseSegments) {
    const list = segmentsByUnit.get(segment.unitId) ?? [];
    list.push(segment);
    segmentsByUnit.set(segment.unitId, list);
  }

  const summaries: TenantSummaryResult[] = [];
  for (const [unitId, segments] of segmentsByUnit) {
    const unitCost = costByUnit.get(unitId) ?? 0;
    const totalDays = segments.reduce((sum, s) => sum + daysBetweenInclusive(s.segmentStart, s.segmentEnd), 0);
    for (const segment of segments) {
      const segmentDays = daysBetweenInclusive(segment.segmentStart, segment.segmentEnd);
      const allocatedCost = totalDays > 0 ? roundCents((unitCost * segmentDays) / totalDays) : 0;
      summaries.push({
        unitId,
        leaseId: segment.leaseId,
        segmentStart: segment.segmentStart,
        segmentEnd: segment.segmentEnd,
        totalAllocatedCostCents: allocatedCost,
      });
    }
  }
  return summaries;
}

export { daysBetweenInclusive, clampDateRange };
